import { Router, type IRouter } from "express";
import authRouter from "./auth";
import productsRouter from "./products";
import categoriesRouter from "./categories";
import brandsRouter from "./brands";
import reviewsRouter from "./reviews";
import blogRouter from "./blog";
import ordersRouter from "./orders";
import newsletterRouter from "./newsletter";
import accountsRouter from "./accounts";
import rolesRouter from "./roles";
import systemRouter from "./system";
import mediaRouter from "./media";
import settingsRouter from "./settings";
import analyticsRouter from "./analytics";
import auditRouter from "./audit";
import couponsRouter from "./coupons";
import digitalCodesRouter from "./digital-codes";
import navigationRouter from "./navigation";

const router: IRouter = Router();

router.use(authRouter);
router.use(productsRouter);
router.use(categoriesRouter);
router.use(brandsRouter);
router.use(reviewsRouter);
router.use(blogRouter);
router.use(ordersRouter);
router.use(newsletterRouter);
router.use(accountsRouter);
router.use(rolesRouter);
router.use(systemRouter);
router.use(mediaRouter);
router.use(settingsRouter);
router.use(analyticsRouter);
router.use(auditRouter);
router.use(couponsRouter);
router.use(digitalCodesRouter);
router.use(navigationRouter);

export default router;
